language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
os:
    - linux
before_install:
    - pip install pytest==3.0.2 pytest-cov==2.3.1
    - pip install coveralls==1.1
install:
    - pip install -e .
after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then
        coveralls;
      fi
script:
    - py.test
